### ISSUE TITLE
Kristupenis ir Mygolas nedirba

### ISSUE THREAD

**Issue by simasbra** [mykolas-milasius/ImmunityTD#51]
labai mazai prisideda prie projekto. pagrinde tik mes su Sarunu pahalinam

**Comment by saharunas** [comment]
axujiel vps

**Comment by MegaManV03** [comment]
![image_2024-04-02_170037201](https://github.com/mykolas-milasius/ImmunityTD/assets/129499066/9747f2e7-535a-4b1c-972f-e227c25a043e)

**Comment by simasbra** [comment]
pradejo dirbt
